---
- name: Configure sudoers for domain admins
  hosts: rhel9
  become: true
  tasks:
    - name: Ensure sudoers file allows domain admins
      lineinfile:
        path: /etc/sudoers.d/domain_admins
        line: '%domain\ admins@NuestraDomain.com ALL=(ALL) ALL'
        create: true
        validate: "visudo -cf %s"
        state: present
        mode: '0440'
