---
- name: Configure static IPv4 on RHEL 9 machines
  hosts: all
  become: true
  tasks:
    - name: Set static IPv4 configuration for ens18
      command: >
        nmcli con mod ens18
        ipv4.addresses 10.0.0.5/24
        ipv4.gateway 10.0.0.254
        ipv4.dns 10.0.0.1
        ipv4.method manual
        connection.autoconnect yes
      changed_when: true

    - name: Bring up the network connection
      command: nmcli con up ens18
      changed_when: true
