---
- name: Check and reboot if needed
  hosts: all
  become: true
  tasks:
    - name: Get system uptime before reboot
      command: uptime -s
      register: uptime_before
      changed_when: false

    - name: Get running kernel version
      command: uname -r
      register: current_kernel
      changed_when: false

    - name: Get latest installed kernel version
      command: rpm -q --last kernel | head -n 1 | awk '{print $1}'
      register: latest_kernel
      changed_when: false

    - name: Print kernel versions
      debug:
        msg: "Running kernel: {{ current_kernel.stdout }}, Latest installed kernel: {{ latest_kernel.stdout }}"

    - name: Reboot if kernel update is detected
      command: /bin/systemctl reboot
      when: "current_kernel.stdout not in latest_kernel.stdout"
      async: 1
      poll: 0
      ignore_errors: true

    - name: Wait for system to come back online
      wait_for_connection:
        delay: 30
        timeout: 300

    - name: Get system uptime after reboot
      command: uptime -s
      register: uptime_after
      changed_when: false

    - name: Print uptime before and after reboot
      debug:
        msg: "Uptime before: {{ uptime_before.stdout }}, Uptime after: {{ uptime_after.stdout }}"

